language: android

jdk:
 - oraclejdk8

android:
  components:
   - tools
   - platform-tools
   - build-tools-24.0.1
   - android-21
   - sys-img-armeabi-v7a-android-21

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_install:
 - chmod +x gradlew

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  # - sys-img-armeabi-v7a-android-22
  # - sys-img-x86-android-17

notifications:
  email: false

sudo: required